[2023-03-20 12:34:25,683] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-20 12:34:25,686] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2023-03-19T00:00:00+00:00 [queued]>
[2023-03-20 12:34:25,686] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 12:34:25,686] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2023-03-20 12:34:25,686] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-20 12:34:25,689] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): greet> on 2023-03-19 00:00:00+00:00
[2023-03-20 12:34:25,691] {standard_task_runner.py:52} INFO - Started process 9792 to run task
[2023-03-20 12:34:25,693] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'our_dag_with_python_operator_v04', 'greet', 'scheduled__2023-03-19T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/var/folders/x1/7qlvjnbj06q1nkyhy70vbb2c0000gn/T/tmp812f512e', '--error-file', '/var/folders/x1/7qlvjnbj06q1nkyhy70vbb2c0000gn/T/tmpxszv7vsn']
[2023-03-20 12:34:25,694] {standard_task_runner.py:77} INFO - Job 45: Subtask greet
[2023-03-20 12:34:25,710] {logging_mixin.py:109} INFO - Running <TaskInstance: our_dag_with_python_operator_v04.greet scheduled__2023-03-19T00:00:00+00:00 [running]> on host Leebyeonghwaui-MacBookPro.local
[2023-03-20 12:34:25,725] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=byeonghwa
AIRFLOW_CTX_DAG_ID=our_dag_with_python_operator_v04
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2023-03-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-19T00:00:00+00:00
[2023-03-20 12:34:25,726] {logging_mixin.py:109} INFO - Hello world! namejerry age20
[2023-03-20 12:34:25,726] {python.py:175} INFO - Done. Returned value was: None
[2023-03-20 12:34:25,728] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_v04, task_id=greet, execution_date=20230319T000000, start_date=20230320T033425, end_date=20230320T033425
[2023-03-20 12:34:25,752] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-20 12:34:25,758] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
